
SET FABRIC_COLORBLEED_DIR=%~dp0
REM Remove trailing backslash if there is one
IF %FABRIC_OPENVDB_DIR:~-1%==\ SET FABRIC_COLORBLEED_DIR=%FABRIC_OPENVDB_DIR:~0,-1%


SET FABRIC_EXTS_PATH=%FABRIC_EXTS_PATH%;%FABRIC_COLORBLEED_DIR%/Exts
SET FABRIC_DFG_PATH=%FABRIC_DFG_PATH%;%FABRIC_COLORBLEED_DIR%/Presets/DFG